---

- name: install git
  yum: name=git state=latest

- name: get repo
  git:
    repo="{{git_repo.url}}"
    version="{{git_repo.branch}}"
    dest="{{git_repo.dest}}"
    clone=yes
    update=yes

- name: check ansible
  yum: name=ansible state=present
  register: ansible_installed

- name: install ansible
  shell: cd mos_mu && source ./install_ansible.sh
  when: ansible_installed is not defined
