---
- hosts: all
  remote_user: rkhozinov
  sudo: yes
  vars:
    sysctl_net_ipv4_ip_forward: 1
    sysctl_net_ipv4_conf_default_rp_filter: 0
    sysctl_net_ipv4_conf_all_rp_filter: 0

  tasks:
    - name: apt update, upgrade, clean
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Configure sysctl
      tags: iptables
      template: src=./sysctl.conf.j2
                dest=/etc/sysctl.conf

    - name: Apply sysctl changes
      tags: iptables
      command: sysctl -p
