---
- hosts: all
  remote_user: root
  sudo: yes
  vars: []
    - { url: 'https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/contrail-5.0-5.0.0-1/contrail-5.0-5.0.0-1.noarch.rpm',
        name: ldap fuel plugin
        destination: contrail.rpm

  tasks:
    - name: get ldap fuel plugin
      get_url:
        url: https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/contrail-5.0-5.0.0-1/contrail-5.0-5.0.0-1.noarch.rpm
        force_basic_auth: yes
        mode: 0400
        dest: /root/contrail.rpm
        with_items:
          - { url: 'https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/contrail-5.0-5.0.0-1/contrail-5.0-5.0.0-1.noarch.rpm',
              name: ldap fuel plugin
              destination: contrail.rpm


    - name: get ldap fuel plugin
      get_url:
        url: http://plugins.mirantis.com/repository/l/d/ldap/ldap-3.0-3.0.0-1.noarch.rpm
        force_basic_auth: yes
        mode: 0400
        dest: /root/ldap.rpm

    - name: get murano fuel plugin
      get_url:
        url: https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/murano-1.1-1.1.0-1/detach-murano-1.1-1.1.0-1.noarch.rpm
        force_basic_auth: yes
        dest: /root/murano.rpm
        mode: 0400

    - name: get stacklight/kibana fuel plugin
      get_url:
        url: https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/StackLight-0.10-0.10.2-1/elasticsearch_kibana-0.10-0.10.2-1.noarch.rpm
        force_basic_auth: yes
        dest: /root/kibana.rpm
        mode: 0400

    - name: get stacklight/grafana fuel plugin
      get_url:
        url: https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/StackLight-0.10-0.10.2-1/influxdb_grafana-0.10-0.10.2-1.noarch.rpm
        force_basic_auth: yes
        dest: /root/grafana.rpm
        mode: 0400

    - name: get stacklight/grafana fuel plugin
      get_url:
        url: https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/StackLight-0.10-0.10.2-1/lma_collector-0.10-0.10.2-1.noarch.rpm
        force_basic_auth: yes
        dest: /root/lma.rpm
        mode: 0400


          fuel plugins --install

    - name: clean additional apt sources
      file: path=/etc/apt/sources.list.d/ state={{item}}
      with_items:
        - absent
        - directory
      tags: clean

    - name: run puppet
      command: puppet agent -tv {{ puppet_server }}
      ignore_errors: yes
      tags: puppet

    - name: get list of sources
      command: ls -l /etc/apt/sources.list.d/
      register: list
      tags: clean

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: remove qemu is at the latest version
      tags: packages
      apt: name={{item}}
           state=absent
           install_recommends=yes
           purge=yes
      with_items:
        - "{{qemu_list}}"

    - name: ensure qemu is at the latest version
      tags: packages
      apt: name={{item}}
           state=latest
           install_recommends=yes
      with_items:
        - "{{qemu_list}}"

    - name: remove libvirt is at the latest version
      tags: packages
      apt: name={{item}}
           state=absent
           install_recommends=yes
           purge=yes
      with_items:
        - "{{libvirt_list}}"

    - name: ensure libvirt is at the latest version
      tags: packages
      apt: name={{item}}
           state=latest
           install_recommends=yes
      with_items:
        - "{{libvirt_list}}"

    - name: configure libvirt
      tags: libvirt
      template: src=../templates/libvirtd.conf.j2
                dest=/etc/libvirt/libvirtd.conf

    - name: configure qemu
      tags: libvirt
      template: src=../templates/qemu.conf.j2
                dest=/etc/libvirt/qemu.conf

    - name: restart libvirt
      tags: libvirt
      service: name=libvirt-bin
               state=restarted

    - name: version
      tags: libvirt
      command: bash -c 'dpkg -l | egrep "(libvirt|qemu)"'

