---
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    storage_endpoint: 172.16.177.5:5000
    fuel_plugins:
      contrail:
        url: "https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/contrail-5.0-5.0.0-1/contrail-5.0-5.0.0-1.noarch.rpm"
        name: contrail
        dest: /root/contrail.rpm
        vcenter_package_url: "http://{{storage_endpoint}}/contrail/5.0/contrail-install-vcenter-plugin_3.2.0.0-25_all.deb"
        vcenter_package_dest: "/var/www/nailgun/plugins/contrail-5.0/"
        contrail_package_url: "http://{{storage_endpoint}}/contrail/5.0/contrail-install-packages_3.1.0.0-25%7eUbuntu-14.04.4-mitaka_all.deb"
        contrail_package_dest: "/var/www/nailgun/plugins/contrail-5.0/"
        contrail_package_run: "/var/www/nailgun/plugins/contrail-5.0/install.sh"

      ldap:
        url: "http://plugins.mirantis.com/repository/l/d/ldap/ldap-3.0-3.0.0-1.noarch.rpm"
        name: ldap
        dest: /root/ldap.rpm

      murano:
        url: "https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/murano-1.1-1.1.0-1/detach-murano-1.1-1.1.0-1.noarch.rpm"
        name: murano
        dest: /root/murano.rpm

      kibana:
        url: "https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/StackLight-0.10-0.10.2-1/elasticsearch_kibana-0.10-0.10.2-1.noarch.rpm"
        name: kibana
        dest: /root/kibana.rpm

      grafana:
        url: "https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/StackLight-0.10-0.10.2-1/influxdb_grafana-0.10-0.10.2-1.noarch.rpm"
        name: grafana
        dest: /root/grafana.rpm

      lma:
        url: "https://3a98d2877cb62a6e6b14-93babe93196056fe375611ed4c1716dd.ssl.cf5.rackcdn.com/StackLight-0.10-0.10.2-1/lma_collector-0.10-0.10.2-1.noarch.rpm"
        name: lma
        dest: /root/lma.rpm

  tasks:
    - name: install git
      tags: prepare
      yum: name=git state=present

    - name: get repo
      tags: prepare
      git:
        repo=https://github.com/aepifanov/mos_mu.git
        version=9.2
        dest=/root/mos_mu
        clone=no
        update=yes

    - name: check ansible
      yum: name=ansible-2.0* state=present
      register: ansible_installed

    - name: install ansible
      tags: prepare
      shell: cd mos_mu && source ./install_ansible.sh
      when: ansible_installed is not defined

    - name: remove plugin packages
      tags: install_plugins
      file:
        path: "{{item.value.dest}}"
        state: absent
      when: "{{ fuel_plugins }}"
      with_dict: "{{ fuel_plugins }}"

    - name: get fuel_plugins
      tags: install_plugins
      get_url:
        url: "{{ item.value.url }}"
        dest: "{{ item.value.dest }}"
        force_basic_auth: yes
      when: "{{ fuel_plugins }}"
      with_dict: "{{ fuel_plugins }}"

    - name: install fuel_plugins
      tags: install_plugins
      shell: >
         fuel plugins --list | grep -q {{ item.value.name }} &&
         echo {{ item.value.name}} has been already installed ||
         fuel plugins --install {{item.value.dest}}
      when: "{{ fuel_plugins }}"
      with_dict: "{{ fuel_plugins }}"

    - name: get contrail vcenter package
      tags: install_plugins, contrail
      get_url:
        url: "{{ item.value.vcenter_package_url }}"
        dest: "{{ item.value.vcenter_package_dest }}"
        force_basic_auth: yes
      when: item.key == "contrail"
      with_dict: "{{ fuel_plugins }}"

    - name: get contrail package
      tags: install_plugins, contrail
      get_url:
        url: "{{ item.value.contrail_package_url }}"
        dest: "{{ item.value.contrail_package_dest }}"
        force_basic_auth: yes
      when: item.key == "contrail"
      with_dict: "{{ fuel_plugins }}"

    - name: install contrail package
      tags: install_plugins, contrail
      shell: "bash -c {{item.value.contrail_package_run}}"
      when: item.key == "contrail"
      with_dict: "{{ fuel_plugins }}"

